### ISSUE TITLE
Setting Custom - MTU Sizes

### ISSUE THREAD

**Issue by egrol** [ibm-cloud-architecture/terraform-openshift4-vmware#14]
Hi Team,

Are we able to include a feature to allow for the change of the MTU sizing for each VM when they get created as part of the initial build phase. Based on our past experiences mainly around the IBM Cloud Paks we've had a need to have increased MTU sizing (jumbo frames) for specific container products (i.e. postgres/couchdb and so on).

**Comment by ncolon** [comment]
Added in latest code drop
