### ISSUE TITLE
Storage VMs - Build

### ISSUE THREAD

**Issue by egrol** [ibm-cloud-architecture/terraform-openshift4-vmware#15]
Hi Team,

Is it possible to setup the build process to allow us to re-use the worker nodes we nominated in the terraform variables to use the worker nodes to setup the storage. Currently the process creates the relevant VMs for the storage nodes. After building out my environment I observed that there was only one disk attached to the worker node VMs. Would it be possible to include an option to include additional disks for each worker VM and include the option to size them accordingly. The idea is to use the raw storage to deploy OCS.

**Comment by ncolon** [comment]
This is not a good practice.

That being said, the **vm** module already exposes the [extra_disk_size](https://github.com/ibm-cloud-architecture/terraform-openshift4-vmware/blob/master/vm/variables.tf#L67-L70) flag which can be added manually to the **compute_vm** module
