### ISSUE TITLE
Typo in main.tf in ignition directory

### ISSUE THREAD

**Issue by slipsibm** [ibm-cloud-architecture/terraform-openshift4-vmware#5]
There is a typo in line 83 of main.tf that causes the install to fail on a linux machine

`if [[ $(uname -s) == "Darwin" ]]; then PLATFORM="mac"; else PLATFOMR="linux"; fi`

The word PLATFORM="linux" is mis-spelled above. Correcting the spelling allows this to work correctly

**Comment by ncolon** [comment]
updated in latest code push
