### ISSUE TITLE
Code doesn't work on VMWare Virtual Cloud Director (VCD) VMWare Shared environment on IBM Cloud

### ISSUE THREAD

**Issue by slipsibm** [ibm-cloud-architecture/terraform-openshift4-vmware#7]
VCD uses a different terraform provider. I forked this repository into slipsibm/terraform-openshift-vmware and modified it to work with VCD. I also tweaked it to support static IP's in VCD because doesn't support the new afterburn ignition strings by adding a fully configured dhcp server to support dhcp reservations. Given the way that you guys have set things up, I'm not sure if this should actually become **ibm-cloud-architecture/terraform-openshift-vmware-cloud-director** vs a branch off the **terraform-openshift-vmware** repository. The only thing left is to clean up (or automate) the setup of the vcd environment. The doc in the readme works but is a little tedious @ncolon

**Comment by ncolon** [comment]
Unable to merge to keep parity with public openshift/installer GitHub repo
