### ISSUE TITLE
Updates to README

### ISSUE THREAD

**Issue by egrol** [ibm-cloud-architecture/terraform-openshift4-vmware#9]
Hi Team,

Suggest adding in some details about the version of terraform and any other underlying packages to be included into the README. I know the versions.tf file has the qualifying requirements in there but from a documentation perspective it's good having to see them within the README as well.

required_version = ">= 0.13"

Regards,

Erol

**Comment by egrol** [comment]
Apologies my poor eye site and reading of the README didn't see:

NOTE: This requires OpenShift 4.6 or later to deploy, if you're looking for 4.5 or earlier, take a look at the pre-4.6 branch

NOTE: Requires terraform 0.13 or later.

**Comment by egrol** [comment]
More updates, is it possible to please also include comments / variables within the terraform.tfvars.example file to include these configuration values:

vsphere_folder
vsphere_preexisting_folder
vsphere_resource_pool
vsphere_preexisting_resourcepool
control_plane_memory
control_plane_num_cpus
compute_memory
compute_num_cpus
storage_memory
storage_num_cpus
openshift_cluster_cidr
openshift_service_cidr
openshift_host_prefix
openshift_version
ssh_public_key

**Comment by ncolon** [comment]
These values are documented in the README.md file.  The sample file is just a sample to get you going.
